
@authToken= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjUiLCJpYXQiOjE3MjM5MDczMDd9.dqt8qh_6FcPsqy1UkLNrjp9v_alydW8bX-u36SMS9kE
@userId = 5 
@authToken2= Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYiLCJpYXQiOjE3MjM5MTI3NzB9.WGLcOyKpKrM7Q5KsK6zySNsU-wfF2bBC9CZ1z7iPHrk
@userId2 = 6
@baseUrl = http://localhost:3000

###register
POST {{baseUrl}}/auth/register
content-type: application/json

{
    "email": "exу324@5334s.com",
    "password": "3243223dfAfd_Svd!",
    "username": "user6"
}

###login
POST {{baseUrl}}/auth/login
content-type: application/json

{
    "email": "exу324@5334s.com",
    "password": "3243223dfAfd_Svd!"
}

### Get User
GET {{baseUrl}}/users/{{userId}}
authorization:  {{authToken}}

###Delete User
DELETE {{baseUrl}}/users/

### Update User
PATCH {{baseUrl}}/users/{{userId}}
authorization:  {{authToken}}
content-type: application/json

{
    "username": "update-user"
} 

### Get Columns
 GET {{baseUrl}}/users/{{userId}}/columns/
authorization:  {{authToken}}

### Get Column for id
GET {{baseUrl}}/users/{{userId}}/columns/2
authorization:  {{authToken}}

### Create Column
POST {{baseUrl}}/users/{{userId}}/columns/
authorization: {{authToken}}
content-type: application/json

{
    "title": "new-columns4"
}

### Update column
PATCH {{baseUrl}}/users/{{userId}}/columns/12
authorization: {{authToken}}
content-type: application/json

{
    "title": "Update-columns2"
}

### Delete Column
DELETE {{baseUrl}}/users/{{userId}}/columns/4
authorization: {{authToken}}

### Get Cards
GET {{baseUrl}}/users/{{userId}}/columns/2/cards/
authorization:  {{authToken}} 

### Create Cards
POST {{baseUrl}}/users/{{userId}}/columns/2/cards/
authorization:  {{authToken}} 
content-type: application/json

{
    "title": "title342",
    "description": "title2-title2"
}

### Update card
PATCH {{baseUrl}}/users/{{userId}}/columns/2/cards/3
authorization: {{authToken}}
content-type: application/json

{
    "description": "title-update-3"
}

### Delete card
DELETE {{baseUrl}}/users/{{userId}}/columns/2/cards/5
authorization: {{authToken}}

### Get comments
GET {{baseUrl}}/users/{{userId}}/columns/2/cards/1/comments
authorization:  {{authToken}} 

### Get comment
GET {{baseUrl}}/users/{{userId}}/columns/2/cards/1/comments/2
authorization:  {{authToken}} 

### Create comment
POST {{baseUrl}}/users/{{userId}}/columns/2/cards/1/comments
authorization:  {{authToken}} 
content-type: application/json

{
    "content": "comm43ent-2"

}

### Update comment
PATCH {{baseUrl}}/users/{{userId}}/columns/2/cards/1/comments/1
authorization:  {{authToken}} 
content-type: application/json

{
    "content": "comment-2"

}

### Delete comment
DELETE {{baseUrl}}/users/{{userId}}/columns/2/cards/5/comments/1
authorization: {{authToken}}