###register
POST http://localhost:3000/auth/register
content-type: application/json

{
    "email": "exу32@534s.com",
    "password": "324423dfAfd_Svd!",
    "username": "user"
}

###login
POST http://localhost:3000/auth/login
content-type: application/json

{
    "email": "exу32@5234s.com",
    "password": "324423dfAfd_Svd!"
}

###
GET http://localhost:3000/users/2
###
DELETE http://localhost:3000/users/2
###
PATCH http://localhost:3000/users/2
content-type: application/json

{
    "email": "exxx345@534s.com"
} 

PATCH http://localhost:3000/users/2
content-type: application/json

{
    "email": "exxx345@534s.com"
} 

###
GET http://localhost:3000/users/1/columns/


###
POST http://localhost:3000/users/1/columns/
content-type: application/json

{
    "title": "new-columns",
    "userId": "3"
} 